### PR TITLE
About this project

### LINKED ISSUE #56: Add area to the site to showcase the devops/maintenance tasks
The pod has worked on a lot of devops-related tasks that aren't instantly visible when you open the web app.

e.g.:

- Github deployment
- Compressed images
- API refactoring
- Netlify 404 fix
- Updating readme

Is there a good way we can expose these changes on the project website? Maybe we could have a modal window that pops up with an "About this project" and list them there?

### PR DESCRIPTION
**Pull request by jcyling**
This PR fixes #56 by adding a modal window with info on how we developed the project. It can be opened by the "About this project" button. It also adds a link to our pod portfolio.

image
image

### CODE REVIEW

**Comment by omeiirr** [comment]
Looks amazing!

Just a small suggestion
Can we make the "About this project" button more prominent?
Currently, it blends well with the background and is easy to miss

image

**Comment by jcyling** [comment]
> Looks amazing!
> 
> Just a small suggestion Can we make the "About this project" button more prominent? Currently, it blends well with the background and is easy to miss
> 
> image


Good idea - I'll try a version with white bg and black text.

**Comment by jcyling** [comment]
> > Looks amazing!
> > Just a small suggestion Can we make the "About this project" button more prominent? Currently, it blends well with the background and is easy to miss
> > image
> 
> Good idea - I'll try a version with white bg and black text.

An update!
image

**Comment by omeiirr** [comment]
Looks great, merging

**Pull request merged**
