### PR TITLE
Add extra fields to weather card

### LINKED ISSUE #39: Improve weather card
Currently, the weather card only shows few info and it doesn't have any graphical elements 
image

So after fixing issue #7, We should add more info from the API response to the card, we can also add some UI elements (clouds, sun etc.) to make it more visually appealing

### PR DESCRIPTION
**Pull request by omeiirr**
closes #39 

Added the following fields to the weather card:
- humidity
- pressure
- windspeed
- sunrise
- sunset

### CODE REVIEW

**Comment by omeiirr** [comment]
Looks like this currently

image

**Comment by keatonmartin** [comment]
I like it a lot! The stats look great! 

It does look like the item icons aren't centered vertically, which looks a little strange. Is it possible to center them?

**Comment by farida52369** [comment]
Looks awesome .. and the changes in the files looks fine to me .. 
But as Keaton said .. if you're good at using CSS can you center the required items? .. i have noticed this problem especially in mobile mood .. but i made it hard coded as i wasn't able to solve it

**Comment by ggongg** [comment]
looks good

**Review by ahmedsaed — COMMENTED** [review]
I like it.

Can you decrease the padding/margin between the lines

**Comment by nightknighto** [comment]
Been too long in opened state, so will merge, and those suggested updates can be made after in a new issue/pull request, and doesn't have to be strictly by omeir since we have no time.

**Pull request merged**
